#!/bin/sh
# ============================================================================
# SENDMAIL WRAPPER FOR MULTISITE
# Determines the domain from current directory and uses per-site msmtp config
# Usage: sendmail-wrapper.sh -t -i (as drop-in replacement for sendmail)
# POSIX-compatible (works with ash/busybox on Alpine)
# ============================================================================

# Configuration
# Runtime configs (copied by entrypoint with correct permissions)
MSMTP_RUNTIME_DIR="${MSMTP_RUNTIME_DIR:-/var/lib/msmtp/sites}"
# Fallback: original mounted configs (may have wrong permissions)
SITES_CONFIG_DIR="${SITES_CONFIG_DIR:-/etc/bitrix-sites}"
DEFAULT_MSMTP_CONFIG="${DEFAULT_MSMTP_CONFIG:-/etc/msmtprc}"
LOG_FILE="${LOG_FILE:-/var/log/msmtp/sendmail-wrapper.log}"
APP_DIR="${APP_DIR:-/home/bitrix/app}"

# Ensure log directory exists
mkdir -p "$(dirname "$LOG_FILE")" 2>/dev/null || true

# Logging function
log() {
    local timestamp
    timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    echo "[$timestamp] $*" >> "$LOG_FILE" 2>/dev/null || true
}

# Determine domain from current working directory
# Expected structure: /home/bitrix/app/{domain}/www/...
get_domain_from_cwd() {
    local cwd
    cwd=$(pwd)

    # POSIX-compatible: strip APP_DIR prefix, then extract first path component
    local path="${cwd#${APP_DIR}/}"
    if [ "$path" != "$cwd" ] && [ -n "$path" ]; then
        # Successfully stripped APP_DIR prefix, get domain (first component)
        echo "${path%%/*}"
        return 0
    fi

    # Fallback: try to get from SCRIPT_FILENAME if set
    if [ -n "${SCRIPT_FILENAME:-}" ]; then
        local spath="${SCRIPT_FILENAME#${APP_DIR}/}"
        if [ "$spath" != "$SCRIPT_FILENAME" ] && [ -n "$spath" ]; then
            echo "${spath%%/*}"
            return 0
        fi
    fi

    return 1
}

# Find msmtp config for domain (checks readability, not just existence)
get_msmtp_config() {
    local domain="$1"

    # Priority 1: mounted config (immediate effect on host file changes, no restart needed)
    local site_config="$SITES_CONFIG_DIR/$domain/msmtp.conf"
    if [ -f "$site_config" ] && [ -r "$site_config" ]; then
        echo "$site_config"
        return 0
    fi

    # Priority 2: runtime copy (fallback when mounted file has wrong permissions)
    local runtime_config="$MSMTP_RUNTIME_DIR/$domain/msmtp.conf"
    if [ -f "$runtime_config" ] && [ -r "$runtime_config" ]; then
        echo "$runtime_config"
        return 0
    fi

    # Priority 3: global fallback (/etc/msmtprc generated by entrypoint)
    if [ -f "$DEFAULT_MSMTP_CONFIG" ] && [ -r "$DEFAULT_MSMTP_CONFIG" ]; then
        echo "$DEFAULT_MSMTP_CONFIG"
        return 0
    fi

    return 1
}

# Main execution
main() {
    local domain=""
    local msmtp_config=""

    # Try to determine domain
    domain=$(get_domain_from_cwd) || domain=""

    if [ -n "$domain" ]; then
        log "Domain detected: $domain (from cwd: $(pwd))"
        msmtp_config=$(get_msmtp_config "$domain") || msmtp_config=""
    fi

    # Fallback to default config if no domain-specific found
    if [ -z "$msmtp_config" ]; then
        if [ -f "$DEFAULT_MSMTP_CONFIG" ] && [ -r "$DEFAULT_MSMTP_CONFIG" ]; then
            msmtp_config="$DEFAULT_MSMTP_CONFIG"
            log "Using default msmtp config: $msmtp_config"
        else
            log "ERROR: No readable msmtp config found! domain=$domain cwd=$(pwd)"
            echo "sendmail-wrapper: No msmtp config found (domain=$domain)" >&2
            exit 1
        fi
    else
        log "Using config: $msmtp_config (domain=$domain)"
    fi

    # Execute msmtp with the determined config
    log "Executing: msmtp -C $msmtp_config $*"
    exec /usr/bin/msmtp -C "$msmtp_config" "$@"
}

# Run main with all script arguments
main "$@"
